-- MySQL Script generated by MySQL Workbench
-- Sat Apr 12 12:25:14 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actividad` (
  `id` INT(10) UNSIGNED NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`centroformacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`centroformacion` (
  `id` INT(10) UNSIGNED NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`programaformacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`programaformacion` (
  `id` INT(10) UNSIGNED NOT NULL,
  `codigo` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(30) NULL DEFAULT NULL,
  `FkIdCentroFormacion` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FkIdCentroFormacion`
    FOREIGN KEY (`FkIdCentroFormacion`)
    REFERENCES `mydb`.`centroformacion` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grupo` (
  `id` INT(10) UNSIGNED NOT NULL,
  `ficha` VARCHAR(15) NOT NULL,
  `cantidadAprendices` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `fechaInicioLectiva` DATE NULL DEFAULT NULL,
  `fechaFinLectiva` DATE NULL DEFAULT NULL,
  `fkIdProgForm` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fkIdProgFrom`
    FOREIGN KEY (`fkIdProgForm`)
    REFERENCES `mydb`.`programaformacion` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rol` (
  `id` INT(10) UNSIGNED NOT NULL,
  `nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT(10) UNSIGNED NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `tipoDocumento` CHAR(2) NOT NULL,
  `documento` VARCHAR(20) NOT NULL,
  `fechaNacimiento` DATE NULL DEFAULT NULL,
  `email` VARCHAR(80) NOT NULL,
  `genero` CHAR(1) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `eps` VARCHAR(20) NULL DEFAULT NULL,
  `tipoSangre` CHAR(3) NOT NULL,
  `peso` DECIMAL(10,0) NULL DEFAULT NULL,
  `estatura` DECIMAL(10,0) NULL DEFAULT NULL,
  `telefonoEmerjencia` VARCHAR(15) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `fkIdRol` INT(10) UNSIGNED NOT NULL,
  `fkIdGrupo` INT(10) UNSIGNED NULL DEFAULT NULL,
  `fkIdCentroFormacion` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fkIdCentroFormacion2`
    FOREIGN KEY (`fkIdCentroFormacion`)
    REFERENCES `mydb`.`centroformacion` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fkIdGrupo`
    FOREIGN KEY (`fkIdGrupo`)
    REFERENCES `mydb`.`grupo` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fkIdRol`
    FOREIGN KEY (`fkIdRol`)
    REFERENCES `mydb`.`rol` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`controlprogreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`controlprogreso` (
  `id` INT(10) UNSIGNED NOT NULL,
  `fechaRealizacion` DATE NOT NULL,
  `peso` DECIMAL(10,0) NULL DEFAULT NULL,
  `cintura` DECIMAL(10,0) NULL DEFAULT NULL,
  `cadera` DECIMAL(10,0) NULL DEFAULT NULL,
  `musloDerecho` DECIMAL(10,0) NULL DEFAULT NULL,
  `musloIsquierdo` DECIMAL(10,0) NULL DEFAULT NULL,
  `brazoDerecho` DECIMAL(10,0) NULL DEFAULT NULL,
  `brazoIzquierdo` DECIMAL(10,0) NULL DEFAULT NULL,
  `antebrazoDerecho` DECIMAL(10,0) NULL DEFAULT NULL,
  `antebrazoIzquierdo` DECIMAL(10,0) NULL DEFAULT NULL,
  `pantorrillaDerecha` DECIMAL(10,0) NULL DEFAULT NULL,
  `pantorrillaIzquierda` DECIMAL(10,0) NULL DEFAULT NULL,
  `examenMedico` VARCHAR(255) NULL DEFAULT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `fechaExamen` DATE NULL DEFAULT NULL,
  `fkIdUsuario` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fkIdUser`
    FOREIGN KEY (`fkIdUsuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`registroingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registroingresos` (
  `id` INT(10) UNSIGNED NOT NULL,
  `fechaIn` DATETIME NOT NULL,
  `fechaOut` DATETIME NULL DEFAULT NULL,
  `fkIdUserGym` INT(10) UNSIGNED NOT NULL,
  `fkIdActividad` INT(10) UNSIGNED NULL DEFAULT NULL,
  `fkIdTrainer` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fkIdActividad`
    FOREIGN KEY (`fkIdActividad`)
    REFERENCES `mydb`.`actividad` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fkIdTrainer`
    FOREIGN KEY (`fkIdTrainer`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fkIdUserGymReg`
    FOREIGN KEY (`fkIdUserGym`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`grupomuscular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grupomuscular` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ejercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ejercicios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `video` VARCHAR(255) NOT NULL,
  `fkIdGrupomuscular` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fkIdGrupomuscular`
    FOREIGN KEY (`fkIdGrupomuscular`)
    REFERENCES `mydb`.`grupomuscular` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rutina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rutina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `calentamiento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ejeRutina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ejeRutina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `series` VARCHAR(5) NOT NULL,
  `repeticones` VARCHAR(5) NOT NULL,
  `descanso` VARCHAR(45) NOT NULL,
  `fkIdEjercicios` INT NOT NULL,
  `fkIdRutina` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fkIdEjercicios`
    FOREIGN KEY (`fkIdEjercicios`)
    REFERENCES `mydb`.`ejercicios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkIdRutina`
    FOREIGN KEY (`fkIdRutina`)
    REFERENCES `mydb`.`rutina` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rutinaUsu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rutinaUsu` (
  `fkIdUsuario` INT(10) UNSIGNED NOT NULL,
  `fkIdRutina` INT NOT NULL,
  CONSTRAINT `fkIdUsuario`
    FOREIGN KEY (`fkIdUsuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkIdRutina`
    FOREIGN KEY (`fkIdRutina`)
    REFERENCES `mydb`.`rutina` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
